import React from "react";
import PropTypes from "prop-types";
import styled from "styled-components";
import Select from "react-select";

interface IDropdown {
  selectedOption?: string;
  handleChange: (v: { value: number; label: string }) => any;
}

const Dropdown: React.FC<IDropdown> = ({ selectedOption, handleChange }) => {
  interface Option {
    label: string;
    value: number;
  }

  const options: Option[] = [
    { value: 1, label: "Afghanistan" },
    { value: 2, label: "Aland Islands" },
    { value: 3, label: "Albania" },
    { value: 4, label: "Algeria" },
    { value: 5, label: "Andorra" },
    { value: 6, label: "Angola" },
    { value: 7, label: "Anguilla" },
    { value: 8, label: "Antigua And Barbuda" },
    { value: 9, label: "Argentina" },
    { value: 10, label: "Armenia" },
    { value: 11, label: "Aruba" },
    { value: 12, label: "Australia" },
    { value: 13, label: "Austria" },
    { value: 14, label: "Azerbaijan" },
    { value: 15, label: "Bahamas" },
    { value: 16, label: "Bahrain" },
    { value: 17, label: "Bangladesh" },
    { value: 18, label: "Barbados" },
    { value: 19, label: "Belarus" },
    { value: 20, label: "Belgium" },
    { value: 21, label: "Belize" },
    { value: 22, label: "Benin" },
    { value: 23, label: "Bermuda" },
    { value: 24, label: "Bhutan" },
    { value: 25, label: "Bolivia" },
    { value: 26, label: "Bosnia And Herzegovina" },
    { value: 27, label: "Botswana" },
    { value: 28, label: "Bouvet Island" },
    { value: 29, label: "Brazil" },
    { value: 30, label: "British Indian Ocean Territory" },
    { value: 31, label: "Brunei" },
    { value: 32, label: "Bulgaria" },
    { value: 33, label: "Burkina Faso" },
    { value: 34, label: "Burundi" },
    { value: 35, label: "Cambodia" },
    { value: 36, label: "Canada" },
    { value: 37, label: "Cape Verde" },
    { value: 38, label: "Cayman Islands" },
    { value: 39, label: "Central African Republic" },
    { value: 40, label: "Chad" },
    { value: 41, label: "Chile" },
    { value: 42, label: "China" },
    { value: 43, label: "Christmas Island" },
    { value: 44, label: "Cocos (Keeling) Islands" },
    { value: 45, label: "Colombia" },
    { value: 46, label: "Comoros" },
    { value: 47, label: "Congo" },
    { value: 48, label: "Congo, The Democratic Republic Of The" },
    { value: 49, label: "Cook Islands" },
    { value: 50, label: "Costa Rica" },
    { value: 51, label: "Croatia" },
    { value: 52, label: "Cuba" },
    { value: 53, label: "Curaçao" },
    { value: 54, label: "Cyprus" },
    { value: 55, label: "Czech Republic" },
    { value: 56, label: "Côte d'Ivoire" },
    { value: 57, label: "Denmark" },
    { value: 58, label: "Djibouti" },
    { value: 59, label: "Dominica" },
    { value: 60, label: "Dominican Republic" },
    { value: 61, label: "Ecuador" },
    { value: 62, label: "Egypt" },
    { value: 63, label: "El Salvador" },
    { value: 64, label: "Equatorial Guinea" },
    { value: 65, label: "Eritrea" },
    { value: 66, label: "Estonia" },
    { value: 67, label: "Ethiopia" },
    { value: 68, label: "Falkland Islands (Malvinas)" },
    { value: 69, label: "Faroe Islands" },
    { value: 70, label: "Fiji" },
    { value: 71, label: "Finland" },
    { value: 72, label: "France" },
    { value: 73, label: "French Guiana" },
    { value: 74, label: "French Polynesia" },
    { value: 75, label: "French Southern Territories" },
    { value: 76, label: "Gabon" },
    { value: 77, label: "Gambia" },
    { value: 78, label: "Georgia" },
    { value: 79, label: "Germany" },
    { value: 80, label: "Ghana" },
    { value: 81, label: "Gibraltar" },
    { value: 82, label: "Greece" },
    { value: 83, label: "Greenland" },
    { value: 84, label: "Grenada" },
    { value: 85, label: "Guadeloupe" },
    { value: 86, label: "Guatemala" },
    { value: 87, label: "Guernsey" },
    { value: 88, label: "Guinea" },
    { value: 89, label: "Guinea Bissau" },
    { value: 90, label: "Guyana" },
    { value: 91, label: "Haiti" },
    { value: 92, label: "Heard Island And Mcdonald Islands" },
    { value: 93, label: "Holy See (Vatican City State)" },
    { value: 94, label: "Honduras" },
    { value: 95, label: "Hong Kong" },
    { value: 96, label: "Hungary" },
    { value: 97, label: "Iceland" },
    { value: 98, label: "India" },
    { value: 99, label: "Indonesia" },
    { value: 100, label: "Iran, Islamic Republic Of" },
    { value: 101, label: "Iraq" },
    { value: 102, label: "Ireland" },
    { value: 103, label: "Isle Of Man" },
    { value: 104, label: "Israel" },
    { value: 105, label: "Italy" },
    { value: 106, label: "Jamaica" },
    { value: 107, label: "Japan" },
    { value: 108, label: "Jersey" },
    { value: 109, label: "Jordan" },
    { value: 110, label: "Kazakhstan" },
    { value: 111, label: "Kenya" },
    { value: 112, label: "Kiribati" },
    { value: 113, label: "Korea, Democratic People's Republic Of" },
    { value: 114, label: "Kosovo" },
    { value: 115, label: "Kuwait" },
    { value: 116, label: "Kyrgyzstan" },
    { value: 117, label: "Lao People's Democratic Republic" },
    { value: 118, label: "Latvia" },
    { value: 119, label: "Lebanon" },
    { value: 120, label: "Lesotho" },
    { value: 121, label: "Liberia" },
    { value: 122, label: "Libyan Arab Jamahiriya" },
    { value: 123, label: "Liechtenstein" },
    { value: 124, label: "Lithuania" },
    { value: 125, label: "Luxembourg" },
    { value: 126, label: "Macao" },
    { value: 127, label: "Macedonia, Republic Of" },
    { value: 128, label: "Madagascar" },
    { value: 129, label: "Malawi" },
    { value: 130, label: "Malaysia" },
    { value: 131, label: "Maldives" },
    { value: 132, label: "Mali" },
    { value: 133, label: "Malta" },
    { value: 134, label: "Martinique" },
    { value: 135, label: "Mauritania" },
    { value: 136, label: "Mauritius" },
    { value: 137, label: "Mayotte" },
    { value: 138, label: "Mexico" },
    { value: 139, label: "Moldova, Republic of" },
    { value: 140, label: "Monaco" },
    { value: 141, label: "Mongolia" },
    { value: 142, label: "Montenegro" },
    { value: 143, label: "Montserrat" },
    { value: 144, label: "Morocco" },
    { value: 145, label: "Mozambique" },
    { value: 146, label: "Myanmar" },
    { value: 147, label: "Namibia" },
    { value: 148, label: "Nauru" },
    { value: 149, label: "Nepal" },
    { value: 150, label: "Netherlands" },
    { value: 151, label: "Netherlands Antilles" },
    { value: 152, label: "New Caledonia" },
    { value: 153, label: "New Zealand" },
    { value: 154, label: "Nicaragua" },
    { value: 155, label: "Niger" },
    { value: 156, label: "Nigeria" },
    { value: 157, label: "Niue" },
    { value: 158, label: "Norfolk Island" },
    { value: 159, label: "Norway" },
    { value: 160, label: "Oman" },
    { value: 161, label: "Pakistan" },
    { value: 162, label: "Palestinian Territory, Occupied" },
    { value: 163, label: "Panama" },
    { value: 164, label: "Papua New Guinea" },
    { value: 165, label: "Paraguay" },
    { value: 166, label: "Peru" },
    { value: 167, label: "Philippines" },
    { value: 168, label: "Pitcairn" },
    { value: 169, label: "Poland" },
    { value: 170, label: "Portugal" },
    { value: 171, label: "Qatar" },
    { value: 172, label: "Republic of Cameroon" },
    { value: 173, label: "Reunion" },
    { value: 174, label: "Romania" },
    { value: 175, label: "Russia" },
    { value: 176, label: "Rwanda" },
    { value: 177, label: "Saint Barthélemy" },
    { value: 178, label: "Saint Helena" },
    { value: 179, label: "Saint Kitts And Nevis" },
    { value: 180, label: "Saint Lucia" },
    { value: 181, label: "Saint Martin" },
    { value: 182, label: "Saint Pierre And Miquelon" },
    { value: 183, label: "Samoa" },
    { value: 184, label: "San Marino" },
    { value: 185, label: "Sao Tome And Principe" },
    { value: 186, label: "Saudi Arabia" },
    { value: 187, label: "Senegal" },
    { value: 188, label: "Serbia" },
    { value: 189, label: "Seychelles" },
    { value: 190, label: "Sierra Leone" },
    { value: 191, label: "Singapore" },
    { value: 192, label: "Sint Maarten" },
    { value: 193, label: "Slovakia" },
    { value: 194, label: "Slovenia" },
    { value: 195, label: "Solomon Islands" },
    { value: 196, label: "Somalia" },
    { value: 197, label: "South Africa" },
    { value: 198, label: "South Georgia And The South Sandwich Islands" },
    { value: 199, label: "South Korea" },
    { value: 200, label: "Spain" },
    { value: 201, label: "Sri Lanka" },
    { value: 202, label: "St. Vincent" },
    { value: 203, label: "Sudan" },
    { value: 204, label: "Suriname" },
    { value: 205, label: "Svalbard And Jan Mayen" },
    { value: 206, label: "Swaziland" },
    { value: 207, label: "Sweden" },
    { value: 208, label: "Switzerland" },
    { value: 209, label: "Syria" },
    { value: 210, label: "Taiwan" },
    { value: 211, label: "Tajikistan" },
    { value: 212, label: "Tanzania, United Republic Of" },
    { value: 213, label: "Thailand" },
    { value: 214, label: "Timor Leste" },
    { value: 215, label: "Togo" },
    { value: 216, label: "Tokelau" },
    { value: 217, label: "Tonga" },
    { value: 218, label: "Trinidad and Tobago" },
    { value: 219, label: "Tunisia" },
    { value: 220, label: "Turkey" },
    { value: 221, label: "Turkmenistan" },
    { value: 222, label: "Turks and Caicos Islands" },
    { value: 223, label: "Tuvalu" },
    { value: 224, label: "Uganda" },
    { value: 225, label: "Ukraine" },
    { value: 226, label: "United Arab Emirates" },
    { value: 227, label: "United Kingdom" },
    { value: 228, label: "United States" },
    { value: 229, label: "United States Minor Outlying Islands" },
    { value: 230, label: "Uruguay" },
    { value: 231, label: "Uzbekistan" },
    { value: 232, label: "Vanuatu" },
    { value: 233, label: "Venezuela" },
    { value: 234, label: "Vietnam" },
    { value: 235, label: "Virgin Islands, British" },
    { value: 236, label: "Wallis And Futuna" },
    { value: 237, label: "Western Sahara" },
    { value: 238, label: "Yemen" },
    { value: 239, label: "Zambia" },
    { value: 240, label: "Zimbabwe" }
  ];

  const customStyles = {
    option: (provided: any) => ({
      ...provided,
      padding: 5
    }),
    menu: (provided: any) => ({
      ...provided,
      marginTop: 0,
      marginBottom: 0,
      minHeight: "15px"
    }),
    menuList: (provided: any) => ({
      ...provided,
      padding: 0
    })
  };

  return (
    <StyledSelect
      value={selectedOption}
      onChange={handleChange}
      options={options}
      placeholder="Choose a country"
      styles={customStyles}
      isSearchable={false}
      menuPlacement="top"
    />
  );
};

Dropdown.propTypes = {
  selectedOption: PropTypes.string,
  handleChange: PropTypes.func.isRequired
};

export default Dropdown;

const StyledSelect = styled(Select)`
  z-index: 2;
  max-width: 250px;
`;
